# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Allen's Blog"
weight = 1

# [zh-cn]
# languageName = "简体中文"
# languagedirection = "ltr"
# title = "Allen's Blog"
# weight = 2

# [zh-tw]
# languageName = "繁體中文"
# languagedirection = "ltr"
# title = "Allen's Blog"
# weight = 2
